language: python
os: linux
dist: xenial

python:
  - "3.7.9"

jobs:
  include:
    - stage: Teste Unitario
      name: "Teste Unitario"
      install:
        - pip install flask
      script:
        - python -m unittest -v test || travis_terminate 1;

    - stage: Deploy Heroku STG
      script: skip
      deploy:
        strategy: api
        provider: heroku
        api_key: $HEROKU_API_KEY
        edge: true
        app: devoposlab-manoed
        on:
          branch: main
                
    - stage: Teste STG
      script:
          - curl https://devoposlab-manoed.herokuapp.com/ | grep Hello || travis_terminate 1;
                
    - stage: Deploy GCP
      script: skip
      deploy:
              provider: gae
              keyfile: ../lab-devops-cloud-edgard-fc3e930b3fc1.json
              project: lab-devops-cloud-edgard
              on:
                      branch: main

    - stage: Teste PRD
      script:
              - curl https://lab-devops-cloud-edgard.uc.r.appspot.com/ | grep Hello || travis_terminate 1;

before_install:
        - openssl aes-256-cbc -K $encrypted_1c83667141a5_key -iv $encrypted_1c83667141a5_iv
          -in lab-devops-cloud-edgard-fc3e930b3fc1.json.enc -out ../lab-devops-cloud-edgard-fc3e930b3fc1.json
          -d
